# Generated by Django 3.1.2 on 2020-11-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201021_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена (BYN)')),
                ('author_book', models.CharField(max_length=200, verbose_name='Автор книги')),
                ('formattt', models.CharField(default=1, max_length=200, verbose_name='Формат')),
                ('isbn', models.CharField(default='', max_length=200, verbose_name='ISBN')),
                ('genres', models.CharField(default='Фантастика', max_length=200, verbose_name='Жанры')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
